### ISSUE TITLE
Logic of is_bigendian() is inverted

### ISSUE THREAD

**Issue by jovermann** [ThBlitz/md5#1]
The function is_bigendian() in sha512.c returns 1 on little-endian machines and 0 on big-endian machines. But the logic in the hash calculation is also inverted to the hashes are correct.

**Comment by th-blitz** [comment]
Apologies for the delayed response; it’s been a while since I last worked on this project. 
I very much appreciate your time in letting me know, have fixed the reversed hash, thank you.
